name: CI
on: 
  watch:
    types: started
jobs:
  build:
    runs-on: windows-lasted
    steps:
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: 1nuyntD8dfclfIhiRqcIOE3pFF2_6UWxtYSHfqg1Y5XUxbhLn
        foreground: false
